### ISSUE TITLE
Top ten view should show both positive and negative in the mini bar

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#235]
Set the secondary progress to the current total, and the primary progress to the positive samples.

See https://www.webcomponents.org/element/PolymerElements/paper-progress/elements/paper-progress

Will also need to add a mixin to the page for the secondary progress, a-la

```css
paper-progress {
  --paper-progress-secondary-color: #f8bbd0;
}
```
